modules.events.RENDER:register(function(delta, ctx)
	local offset = vec(0, previous.pose == "CROUCHING" and 2.25 or 0, 0)
	models.cat:setPos(models.cat:getPos() + offset)
	models.cat.Body:setPos(offset)
	models.cat.RightArm:setPos(offset)
	models.cat.LeftArm:setPos(offset)
	models.cat.Head:setPos(offset)

	models.cat.RightLeg:setPos(previous.pose == "CROUCHING" and vec(0, -1, 1) or nil)
	models.cat.RightLeg:setRot(previous.pose == "CROUCHING" and vec(12.5, 0, 0) or nil)
	models.cat.LeftLeg:setPos(previous.pose == "CROUCHING" and vec(0, -1, 1) or nil)
	models.cat.LeftLeg:setRot(previous.pose == "CROUCHING" and vec(12.5, 0, 0) or nil)
end)
